print('='*10 + ' CALCULADORA DE ÁREA ' + '='*10)
print('')
altura = float(input('Insira a medida da altura em metros: '))
largura = float(input('Insira a medida da largura em metros: '))
print('')
area = altura * largura
print('='*15 + ' RESULTADO ' + '='*15)
print('')
print(f'A área calculada é de {area}m.')
print('')
print('='*41)