#Faça um programa em que o usuário precisa cadastrar nome, idade, telefone e e-mail. Depois mostre os valores digitados na tela.

print('='*10 + ' CADASTRO DE USUÁRIO ' + '='*10)
nome = input('Nome: ')
idade = input('Idade: ')
telefone = input('Telefone: ')
email = input('E-mail: ')
print(' ')
print(' ')
print('='*10 + ' USUÁRIO  CADASTRADO ' + '='*10)
print(f'NOME: {nome}')
print(f'IDADE: {idade} anos')
print(f'TELEFONE: {telefone}')
print(f'E-MAIL: {email}')
print('='*41)